config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
  root "home#index"

  #Api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, Post
    else
      can :read, Post
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  def increment_comments_count
    post = Post.find_by(id: post_id)
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  def increment_likes_count
    post = Post.find_by(id: post_id)
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  def increment_post_counter
    user = User.find(author_id)
    user.increment!(:posts_counter)
  end

  def five_recent_comments
    Comment.where(post_id: id).order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, foreign_key: 'author_id'
  has_many :like
  has_many :comment

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def admin?
    role.include?('admin')
  end

  def three_recent_posts
    Post.where(author_id: id).order(created_at: :desc).limit(3)
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::API
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::ApiController
  before_action :find_user_post

  def index
    @comments = @post.comments

    render json: @comments, include: ['user']
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.author = @user

    if @comment.save
      render json: @comment, status: :created
    else
      render json: { error: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def find_user_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::ApiController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts

    render json: @posts, include: %w[author comments]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.find(1)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    post = Post.find(params[:post_id])
    new_comment = post.comments.build(comments_params)
    new_comment.user_id = current_user.id

    respond_to do |c|
      if new_comment.save
        new_comment.increment_comments_count
        c.html { redirect_to user_post_url(current_user.id, post.id) }
      else
        c.html { render 'posts/show' }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to user_post_url, notice: 'Comment deleted successfully'
  end

  private

  def comments_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    new_like = @post.likes.build(user_id: @user.id)

    respond_to do |c|
      new_like.increment_likes_count if new_like.save
      c.html { redirect_to user_post_url(current_user.id, @post.id) }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = @user.posts.includes(:comments)
  end

  def new
    @post = Post.new
  end

  def show; end

  def create
    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to user_post_url(@user.id, @post.id), notice: 'Post was successfully created!'
    else
      flash.now[:alert] = 'Post could not be created!'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(author_id: params[:id])
  end

  private

  def set_user; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: @comment, url: user_post_comments_url, local: true)  do |form| %>
    <div>
        <%= form.label :text %>
        <br />
        <%= form.text_area :text %>
        <br />
        <br />
    </div>
    <%= form.submit %>
<% end %>

app/views/comments/new.html.erb
<h1>Enter comment for post "<%= @post.title %>"</h1>

<%= render 'form' %>

app/views/home/_navbar.erb
<nav>
    <h1 class='header'>
        <%= link_to "Home", root_url %>
        </h1>
    <h2>
        <% if @user %>
            <%= @user.admin? ? 'Admin' : 'User' %>
        <% end %>
    </h2>
    <ul>
            <li>
                <%= link_to "See Users", users_url %>
            </li>
    </ul>
</nav>

app/views/home/index.erb
<h1>Welcome to my Blog App</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class='container'>
      <% if notice %>
        <p class="#{us}"><%= notice %></p>
      <% elsif alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with(model: Like.new, url: user_post_likes_url(@user, @post), local: true)  do |form| %>
    <%= form.submit 'like' %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: @post, url: user_posts_url, local: true)  do |form| %>
    <% if @post.errors.any? %>
      <div>
        <h2><%= pluralize(@post.errors.count, "error") %></h2>

        <ul>
          <% @post.errors.full_messages.each do |message|%>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :title %>
      <br />
      <%= form.text_field :title %>
      <br />
      <br />
    </div>
    
    <div>
      <%= form.label :text %>
      <br />
      <%= form.text_field :text %>
      <br />
      <br />
    </div>

    <%= form.submit %>
<% end %>

app/views/posts/index.html.erb
<img src="<%= @user.photo%>"/>
<h1><%= @user.name %></h1>
<p>Posts: <%= @user.posts_counter%></p>


<% @posts.each do |post| %>
    <%= link_to "See #{post.title}", user_post_url(@user.id, post.id) %>
    <h2>Title: <%= post.title %></h2>
    <p>Text: <%= post.text %></p>
    <span>Likes : <%= post.likes_counter %></span>

    <span>Comments : <%= post.comments_counter %></span>
    <%= link_to "show post", user_post_url(@user.id, post.id) %>
    <% post.five_recent_comments.each do |comment| %>
        <p>Comment: <%= comment.text %></p>
    <%end%>
<% end %>

app/views/posts/new.html.erb
<h1>Add new Post</h1>

<%= render 'form' %> 

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.text ? @post.text : 'No text' %></>
<h1><%= @post.comments_counter %></h1>
<span><%= render 'likes/form' %><%= @post.likes_counter %></span>
<h3>Comments</h3>
<% @post.five_recent_comments.includes(:user).each do |comment| %>
    <p><%= comment.user.name %> : <%= comment.text %></p>
<% end %>
<%= link_to "Add comment", new_user_post_comment_url(@user.id, @post.id)%>

app/views/users/index.html.erb
<h1>Users Page</h1>
<% @users.each do |user| %>
    <img src="<%= user.photo%>"/>
    <h3>user: <%= user.name %></h3>
    <p>Bio: <%= user.bio ? user.bio : 'No Bio' %></p>
    <p>Posts: <%= user.posts_counter%>
    <%= link_to "show #{user.name}", user %>
<% end %>

app/views/users/show.html.erb
<img src="<%= @user.photo%>"/>
<h1><%= @user.name %></h1>
<p><%= @user.bio ? @user.bio : 'No bio' %></p>
<p>Posts: <%= @user.posts_counter%></p>

<ul>
    <% @posts.empty? ? 'No post available' : @user.three_recent_posts.each do |post| %>
        <li>
            <h2>Title: <%= post.title %></h2>
            <p>Text: <%= post.text %></p>
            <span>likes: <%= post.likes_counter %></span>
            <span>Comments: <%= post.comments_counter %></span>
            <%= link_to "See #{post.title}", user_post_url(@user.id, post.id) %>
        </li>
    <% end %>
    <br/>
    <%= link_to 'See all posts', user_posts_path(@user.id) %>
</ul>